name: Install Debutizer
description: Installs Debutizer via APT

runs:
  using: composite
  steps:
  - name: Install Debutizer
    uses: myci-actions/add-deb-repo@10
    with:
      repo: deb http://apt.debutizer.dev focal main
      repo-name: debutizer
      keys-asc: https://raw.githubusercontent.com/velovix/debutizer/main/debutizer.key
      install: debutizer
