name: Production Release

on:
  push:
    branches:
      - main

jobs:
  s3-repo-upload:
    runs-on: ubuntu-20.04
    environment: prod
    steps:
      - uses: actions/checkout@v2
      - name: Build
        uses: ./.github/actions/debutizer-build
        with:
          config_file: debutizer.prod.yaml
      - name: Upload
        run: debutizer upload --config-file debutizer.prod.yaml
        env:
          DEBUTIZER_ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
          DEBUTIZER_SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DEBUTIZER_GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
          DEBUTIZER_GPG_SIGNING_PASSWORD: ${{ secrets.GPG_SIGNING_PASSWORD }}
  ppa-upload:
    needs: s3-repo-upload
    runs-on: ubuntu-20.04
    environment: prod
    steps:
      - uses: actions/checkout@v2
      - name: Install Debutizer
        uses: ./.github/actions/debutizer-install
      - name: Source
        run: debutizer source --config-file debutizer.ppa.yaml
      - name: Upload
        run: debutizer upload --config-file debutizer.ppa.yaml
        env:
          DEBUTIZER_GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
          DEBUTIZER_GPG_SIGNING_PASSWORD: ${{ secrets.GPG_SIGNING_PASSWORD }}
