name: Production Release

on:
  push:
    branches:
      - main

jobs:
  deploy-packages:
    runs-on: ubuntu-20.04
    environment: prod
    steps:
      - uses: actions/checkout@v2
      - name: Build
        uses: ./.github/actions/debutizer-build
      - name: Upload APT Packages
        run: debutizer s3-repo upload --profile prod
        env:
          DEBUTIZER_ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
          DEBUTIZER_SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DEBUTIZER_GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
          DEBUTIZER_GPG_SIGNING_PASSWORD: ${{ secrets.GPG_SIGNING_PASSWORD }}
