name: Staging Release

on: [push]

jobs:
  s3-repo-upload:
    runs-on: ubuntu-20.04
    environment: stage
    steps:
      - uses: actions/checkout@v2
      - name: Build
        uses: ./.github/actions/debutizer-build
        with:
          config_file: debutizer.stage.yaml
      - name: Upload
        run: debutizer upload --config-file debutizer.stage.yaml
        env:
          DEBUTIZER_ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
          DEBUTIZER_SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DEBUTIZER_GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
          DEBUTIZER_GPG_SIGNING_PASSWORD: ${{ secrets.GPG_SIGNING_PASSWORD }}
